"""rename_date_start_drop_date_end_add_name_normalized

Revision ID: 16faa74af217
Revises: 1b8f621d064e
Create Date: 2026-05-31 21:02:00.337240
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic
revision: str = '16faa74af217'
down_revision: Union[str, None] = '1b8f621d064e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('name_normalized', sa.String(), nullable=False))
    op.alter_column('events', 'date_start', new_column_name='event_date')
    op.drop_column('events', 'date_end')
    op.add_column('venues', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('venues', 'latitude')
    op.drop_column('venues', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('longitude', sa.FLOAT(), nullable=True))
    op.add_column('venues', sa.Column('latitude', sa.FLOAT(), nullable=True))
    op.drop_column('venues', 'url')
    op.add_column('events', sa.Column('date_end', sa.DateTime(), nullable=True))
    op.alter_column('events', 'event_date', new_column_name='date_start')
    op.drop_column('cities', 'name_normalized')
    # ### end Alembic commands ###
